
[[pools]]
address = "addr1z8nvjzjeydcn4atcd93aac8allvrpjn7pjr2qsweukpnaytvcg6zm2vds6mz9x3h3yalqmnf24w86m09n40q3tgqxjms9yu6v8"
token1 = "Ada"
token2 = "57696e67526964657273"

[[pools]]
address = "addr1z8nvjzjeydcn4atcd93aac8allvrpjn7pjr2qsweukpnayvwn8ns9d9rn074cn39gdlnzq8gneqxtektt3etelutfgysw42u27"
token1 = "Ada"
token2 = "DANA"
