//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "raw_token_transfer")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub output_id: i64,
    pub policy_id: Vec<u8>,
    pub name: Vec<u8>,
    pub amount: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::raw_transaction_output::Entity",
        from = "Column::OutputId",
        to = "super::raw_transaction_output::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    RawTransactionOutput,
}

impl Related<super::raw_transaction_output::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RawTransactionOutput.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
